# Generated by Django 3.2 on 2021-06-25 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210625_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=100)),
                ('invoice_for', models.CharField(default='', max_length=255)),
                ('user', models.CharField(default='', max_length=100)),
                ('vendor', models.CharField(default='', max_length=100)),
                ('rml', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('total_igst', models.IntegerField(default=0)),
                ('total_sgst', models.IntegerField(default=0)),
                ('total_cgst', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('remark', models.CharField(default='', max_length=1000)),
                ('po_no', models.IntegerField(default=0)),
                ('terms', models.CharField(default='', max_length=1000)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 9, 51, 21, 917567))),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2021, 6, 25, 9, 51, 21, 917567))),
                ('total_gst', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Invoice_Model',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='admins.invoice_model')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
    ]
