# Generated by Django 3.2 on 2021-06-25 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_invoice_invoice_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_model',
            name='project',
        ),
        migrations.AddField(
            model_name='invoice_model',
            name='invoice_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 3, 46, 823126)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 3, 46, 823126)),
        ),
    ]
