# Generated by Django 3.2 on 2021-06-25 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20210625_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_model',
            old_name='invoice_for',
            new_name='supplier_invoice_no',
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 8, 3, 10888)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 8, 3, 10888)),
        ),
    ]
