# Generated by Django 3.2 on 2021-06-25 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20210625_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_model',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='invoice_model',
            name='supplier_invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 12, 56, 446839)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 12, 56, 446839)),
        ),
    ]
