# Generated by Django 3.2 on 2021-06-25 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20210625_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_model',
            old_name='remark',
            new_name='naration',
        ),
        migrations.RenameField(
            model_name='invoice_model',
            old_name='vendor',
            new_name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='invoice_model',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice_model',
            name='po_no',
        ),
        migrations.RemoveField(
            model_name='invoice_model',
            name='rml',
        ),
        migrations.RemoveField(
            model_name='invoice_model',
            name='terms',
        ),
        migrations.AddField(
            model_name='invoice_model',
            name='supplier_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='supplier_invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 36, 13, 713980)),
        ),
    ]
