# Generated by Django 3.2 on 2021-06-25 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_auto_20210625_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_model',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='supplier_invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 48, 58, 607276)),
        ),
    ]
