# Generated by Django 3.2 on 2021-06-25 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20210625_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='supplier_invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 12, 52, 12, 126010)),
        ),
    ]
